apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: ${SERVICE_NAME}
  labels:
    tsLogWatch: ${SERVICE_NAME}
spec:
  kafka:
    template:
      statefulset:
        metadata:
          labels:
            tsLogWatch: ${SERVICE_NAME}
    version: 3.3.1
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "3.1-IV0"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral